# Name of this GitHub Actions workflow.
name: StartLeft

on:
  # Scan changed files in PRs (diff-aware scanning):
  #pull_request: {}
  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch: {}
  # Scan mainline branches and report all findings:
  push:
    branches: ["master", "main"]
  # Schedule the CI job (this method uses cron syntax):
  schedule:
    - cron: '33 13 * * 4' # Sets schedule to scan every Wed at 13:33 UTC.
    # It is recommended to change the schedule to a random time.

jobs:
  sls:
    # User definable name of this GitHub Actions job.
    name: sls/scan
    # If you are self-hosting, change the following `runs-on` value: 
    runs-on: ubuntu-latest

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      # Fetch project source with GitHub Actions Checkout.
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
  
      - name: Restore dependencies
        run: dotnet restore
  
      - name: Build the solution
        run: dotnet build --no-restore --configuration Release

      - name: Run SLS Scanner
        uses: tauruseer/sls-pipeline-scanner@v1.2.1
        with:
          scanKey: ${{ secrets.SLS_SCAN_KEY }}
          username: ${{ secrets.SLS_CLIENT_ID }}
          password: ${{ secrets.SLS_CLIENT_SECRET }}
          runSCA: 'true'
          runSAST: 'true'
          runGitLeaks: 'true'
